# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.15

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
