# https://github.com/elastic/logstash-docker
FROM docker.elastic.co/logstash/logstash:5.5.1
RUN logstash-plugin install logstash-input-http

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
