version: '2'

services:
  serilog-example:
    build:
      context: .
    environment: 
      USE_LOGSPOUT:
    networks:
      - elastic-stack_elk

networks: 
  elastic-stack_elk:
    external: true