name: CI/CD

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - run: docker-compose -f elastic-stack/docker-compose.yml build
      - run: docker-compose -f serilog/docker-compose.yml build
